### ISSUE TITLE
Error when setting widget visibility

### ISSUE THREAD

**Issue by marpa** [clas-web/clas-buttons#1]
When the visibility of this widget is updated to "show if page is front page" the following error is displayed:
`Warning: trim() expects parameter 1 to be string, array given in /home/pages/public_html/wp-content/plugins/clas-buttons/control.php on line 177`

error is only displayed when the widget is visible

**Comment by atrus1701** [comment]
7028679e9d9c5aee2fb2d6289a963d874e6636e8
